#!/usr/bin/env php
<?php

set_include_path( dirname( __FILE__ ) . '/source' . PATH_SEPARATOR . get_include_path() );

require_once 'PHP/ChangeCoverage/Autoloader.php';

$autoloader = new PHP_ChangeCoverage_Autoloader( dirname( __FILE__ ) . '/library' );
$autoloader->register();

$command = new PHP_ChangeCoverage_TextUI_Command();
exit( $command->run( $_SERVER['argv'] ) );